// **********************************************************************
// Parsed By TarsParser(2.4.5), Generated By tars2node(20200707)
// TarsParser Maintained By <TARS> and tars2node Maintained By <superzheng>
// Generated from "QueryF.tars" by Imp Mode
// **********************************************************************

"use strict";

const TarsStream = require("@tars/stream");
const TarsError = require("@tars/rpc").error;

const tars = require("./QueryF.js").tars;
module.exports.tars = tars;

tars.QueryFImp.prototype.initialize = function () {
};

tars.QueryFImp.prototype.findObjectById = function (current, id) {
    
};


